# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
addons:
    apt:
        packages:
            - hdf5-tools
matrix:
    allow_failures:
    - julia: nightly
# This waits 20 minutes; necessary for the benchmarking to complete
# UPDATE: it fails https://travis-ci.org/cstjean/TraceCalls.jl/jobs/272448867
# install: travis_wait mvn install
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -p 2 -e 'Pkg.clone(pwd()); Pkg.build("TraceCalls"); Pkg.test("TraceCalls"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("TraceCalls")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("TraceCalls")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
